---
- name: install puppet
  yum: name='puppet' state=present
  tags: ['install_puppet_client']

- name: copy puppet config
  template: src='puppet.conf' dest='/etc/puppet/puppet.conf'
  tags: ['configure_puppet_client']

- name: request cert to be signed on puppetmaster
  command: "puppet agent --test --noop"
  #sudo: yes
  register: puppet_result
  args:
    creates: "/var/lib/puppet/ssl/certificate_requests/{{ ansible_fqdn }}.pem"
  failed_when: (puppet_result.rc != 1) and (puppet_result.rc != 0)
  tags: ['puppet_cert_bootstrap']

- name: sign cert on puppetmaster
  command: "puppet cert sign {{ ansible_fqdn }}"
  remote_user: "{{ lookup('env', 'USER') }}"
  sudo: yes
  args:
    removes: "/var/lib/puppet/ssl/ca/requests/{{ ansible_fqdn }}.pem"
  delegate_to: "{{ puppetmaster }}"
  tags: ['puppet_cert_bootstrap']

- name: puppetize!
  command: "puppet agent -t"
  #sudo: yes
  register: puppet_result
  failed_when: (puppet_result.rc != 2) and (puppet_result.rc != 0)
  tags: ['puppet_run']
